# Generated by Django 3.2.8 on 2021-10-05 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanner',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 13, 24, 9, 631317)),
        ),
        migrations.AlterField(
            model_name='scanner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
