# Generated by Django 3.2.8 on 2021-10-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=256)),
                ('current', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
