# Generated by Django 3.2.8 on 2021-10-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_auto_20211018_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupprogress',
            name='target_type',
            field=models.CharField(default='collection', max_length=256),
        ),
    ]
