# Generated by Django 3.2.8 on 2021-10-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_backupprogress_target_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backupprogress',
            old_name='target',
            new_name='database',
        ),
        migrations.RemoveField(
            model_name='backupprogress',
            name='target_type',
        ),
        migrations.AddField(
            model_name='backupprogress',
            name='collection',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
