# Generated by Django 3.2.8 on 2021-10-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_auto_20211018_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupprogress',
            name='collection',
            field=models.CharField(default='', max_length=256),
        ),
    ]
